cookie:
  expiry_days: 30
  key: LLMDemoKey
  name: Positive_Demo
credentials:
  usernames:
    admin:
      access_level: top
      email: admin@example.com
      name: Demo User
      password: $2b$12$abcdefghijklmnopqrstuuabcdefghijklmnopqrstuvwxABCDEFG
    demo:
      access_level: demo
      email: demo@example.com
      name: Demo User
      password: $2b$12$abcdefghijklmnopqrstuuabcdefghijklmnopqrstuvwxABCDEFG
preauthorized:
  emails:
  - user@example.com
