cookie:
  expiry_days: 30
  key: LLMDemoKey
  name: Positive_Demo
credentials:
  usernames:
    admin:
      access_level: Admin
      email: admin@example.com
      name: Demo User
      password: $2b$12$abcdefghijklmnopqrstuuabcdefghijklmnopqrstuuabcdefghi
    demo:
      access_level: Demo
      email: demo@example.com
      name: Demo User
      password: $2b$12$abcdefghijklmnopqrstuuabcdefghijklmnopqrstuuabcdefghi
preauthorized:
  emails:
  - user@example.com

